<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Notepads.WebInstaller</RootNamespace>
    <AssemblyName>NotepadsInstaller</AssemblyName>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <StartupObject>Notepads.WebInstaller.Program</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

</Project>
